name: sps
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_pdfview: ^1.0.4
  dio: ^3.0.10
  flutter_isolate: ^1.0.0+15
  cron: ^0.2.4
  flutter_local_notifications: ^4.0.1+2
  exif:
  flutter:
    sdk: flutter
  splashscreen: ^1.2.0
  scoped_model: ^1.0.1
  rflutter_alert: ^1.0.3
  flutter_plugin_android_lifecycle: ^1.0.2
  image_picker_platform_interface: ^1.1.0
  image_picker: ^0.6.7+14
  url_launcher: ^5.4.0
  media_gallery: ^0.1.5
  transparent_image:
  permission_handler:
  auto_orientation: ^1.0.6
  chewie: ^0.12.0
  flutter_localizations:
    sdk: flutter
  datetime_picker_formfield: ^1.0.0
  mask_text_input_formatter: ^1.2.1
  flutter_masked_text: ^0.7.0
  scrollable_positioned_list: ^0.1.10
  video_thumbnail: ^0.2.5
  path_provider: ^1.6.27

  # Dependências para o DB
  sqflite:
  path:
  http:
  http_interceptor:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  video_player: ^1.0.0
  flutter_test:
    sdk: flutter
  intl: ^0.16.0
  grouped_checkbox: 1.0.0
  flutter_launcher_icons: "^0.8.1"
  media_gallery:
  lint: ^1.3.0
  connectivity: ^0.4.8+1
  extended_image: ^1.5.0
  image: any
  loading_overlay: ^0.2.1
  badges: ^1.1.6
  scroll_to_index: ^1.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path: "images/icone.png"
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo_schuler.gif
    - images/logo_sps.png
    - images/desenvolvimento.png
    - images/negativo.png
    - images/positivo.png
    - images/noimage.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

